/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.16                       *
*        Compiled Jun  4 2012, 15:48:50                              *
*        (C) 1998 - 2011 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: HZ_HWXW24.c                                           *
* Font:        »ªÎÄÐÂÎº                                              *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 24                                            *
* Range disabled: 0000 - FFFF                                        *
* Read pattern file: R:\HZ_HJR.txt                                   *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHZ_HWXW24;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontHZ_HWXW24_516C[ 51] = { /* code 516C */
  ________,X_______,________,
  ________,XX______,________,
  ________,XXX_____,________,
  ________,_XXX____,________,
  ______X_,__XXX___,________,
  _____XX_,___XX___,________,
  ____XXX_,____XX__,________,
  ____XX__,X____XX_,________,
  ___XX__X,XX____XX,________,
  __XX___X,XX_____X,X_______,
  _XXX__XX,X______X,XXX_____,
  XXX___XX,___X___X,XXXX____,
  X____XX_,_XX_X___,__XXX___,
  ____XXXX,XX___X__,________,
  ___XXXXX,XX__XX__,________,
  ___XXXXX,X__XXXX_,________,
  ____X___,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ_HWXW24_53F8[ 34] = { /* code 53F8 */
  ________,_XXXXX__,
  _____XXX,XXXXXXX_,
  ___XXXXX,___XXX__,
  ___X____,____XX__,
  ______XX,X___XX__,
  ___XXXXX,XX__XX__,
  XXXXXX__,____XX__,
  X_______,____XX__,
  ____XXXX,X___XX__,
  _XXXXXXX,X___XX__,
  _XXX__XX,X___XX__,
  _XXX__XX,____XX__,
  __XXXXXX,____XX__,
  ___XX__X,____XX__,
  ________,XXXXXX__,
  ________,__XXXX__,
  ________,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ_HWXW24_5733[ 60] = { /* code 5733 */
  ________,________,________,
  ________,_______X,X_______,
  ___XX___,_______X,X_______,
  ___XX___,_______X,________,
  ___XX___,XX_____X,________,
  ___X____,X_XX___X,________,
  ___X____,X_XX___X,________,
  ___XXXX_,X_XX___X,________,
  XXXXXXX_,X_XX___X,________,
  XXXXXX__,X_XX___X,________,
  _XXXX___,X_XX___X,________,
  ___XXX_X,X_XX___X,________,
  ___XXX_X,__X____X,________,
  __XXX__X,_______X,________,
  _XXX__XX,_______X,________,
  XXX__XX_,_______X,X_______,
  _X__XX__,_______X,X_______,
  ________,_______X,X_______,
  ________,_______X,X_______,
  ________,_______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ_HWXW24_597D[ 54] = { /* code 597D */
  _______X,X______X,X_______,
  _______X,X___XXXX,XXX_____,
  _______X,__XXX___,XX______,
  _______X,___X___X,X_______,
  _______X,_XX__XXX,________,
  ______XX,_XX___XX,________,
  ______XX,XX____XX,X_______,
  ____XXXX,XX___XXX,XXXXX___,
  _XXXXXX_,_XXXXXXX,XXXXX___,
  _XXX_XX_,XXXXX__X,X_______,
  _____XX_,X______X,X_______,
  ______XX,X______X,X_______,
  ______XX,XXX____X,X_______,
  ___XXX__,_XX____X,X_______,
  ____X___,_XX____X,X_______,
  ________,______XX,________,
  ________,___XXXXX,________,
  ________,______XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ_HWXW24_5E02[ 69] = { /* code 5E02 */
  ________,X_______,________,
  ________,X_______,________,
  _______X,XXX_____,________,
  ________,_XX_____,________,
  ________,___XXXXX,XX______,
  _____XXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,_XX_____,
  XXX_____,XXX_____,________,
  ________,XXXXXXX_,________,
  ____XXXX,XX___XXX,________,
  ____XXX_,_X___XX_,________,
  ____XX__,_X___XX_,________,
  ____XX__,_X___XX_,________,
  _____X__,_X___XX_,________,
  _____X__,_XXXXXX_,________,
  ________,_X__XXX_,________,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ_HWXW24_6280[ 54] = { /* code 6280 */
  ______X_,____XX__,________,
  ______X_,____XX__,________,
  _____XX_,____XX__,________,
  _____XX_,____XX__,________,
  _____XXX,____XXXX,________,
  ___XXXXX,____XXXX,X_______,
  _XXXXXX_,_XXXXXX_,________,
  __X__XX_,_XX_X___,________,
  _____XX_,____X___,________,
  _____X__,___XXXXX,________,
  ___XXX__,___X_XX_,________,
  __XXXX__,_XX__XX_,________,
  XXX__X__,__XXXX__,________,
  _X___X__,___XXX__,________,
  _____X__,__XXXXX_,________,
  ___XXX_X,XXX___XX,X_______,
  _____X__,______XX,XXXX____,
  ________,________,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ_HWXW24_6709[ 60] = { /* code 6709 */
  ________,__X_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX__XXX,XX______,
  ________,XXXXXXXX,XX______,
  ___XXXXX,XXX_____,________,
  __XXXXXX,X_______,________,
  _______X,XXXXXXX_,________,
  _______X,XX___XX_,________,
  ______XX,X____XX_,________,
  _____X_X,XXX__XX_,________,
  ____X__X,XX___XX_,________,
  __XXX__X,X____XX_,________,
  _XX____X,XXX__XX_,________,
  _______X,XX___XX_,________,
  _______X,_____XX_,________,
  _______X,_____XX_,________,
  _______X,_____XX_,________,
  _______X,__XXXXX_,________,
  ________,____XXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ_HWXW24_6DA6[ 32] = { /* code 6DA6 */
  __X____X,________,
  __XX___X,___XXXXX,
  __XXX__X,XXX__XXX,
  ___XX___,X_____XX,
  ________,______XX,
  _X___X__,_XXX__XX,
  XXX__X_X,XXX___XX,
  XX__XX__,_XXX__XX,
  X___XX_X,XXX___XX,
  X___XX__,_XX___XX,
  X__X_X_X,XXXXX_XX,
  X__X_XXX,______XX,
  X__X_X__,______XX,
  _XX__X__,__X___XX,
  _XX__X__,___XXXXX,
  ________,_____XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ_HWXW24_6DF1[ 51] = { /* code 6DF1 */
  ________,____XXXX,________,
  __X_____,XXXXX__X,X_______,
  __XX___X,_XX_X__X,X_______,
  __XXX_XX,_X__X_XX,________,
  ______XX,_X__X___,________,
  ________,_X__XXX_,________,
  _XX_____,X_______,________,
  _X______,___XXXXX,________,
  XX__X___,_XXXXXXX,________,
  X___X_XX,XXXXX___,________,
  X___X__X,__XXXX__,________,
  X__XX___,_XXXXXX_,________,
  X_XX____,XX_X__XX,X_______,
  XXXX___X,X__X___X,XXXX____,
  _XX__XX_,___X____,XXXXX___,
  ________,___X____,________,
  ________,_XXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ_HWXW24_79D1[ 66] = { /* code 79D1 */
  ________,______X_,________,
  ________,______XX,________,
  ______XX,X_____X_,________,
  ____XX__,______X_,________,
  ___XXX__,__X___X_,________,
  ________,__XX__X_,________,
  ______XX,___XX_X_,________,
  __XXXXXX,______X_,________,
  _XXXXXX_,__XX__X_,________,
  _X__XXX_,__XX__X_,________,
  ___XXXXX,______XX,XXX_____,
  ___X_XX_,___XXXXX,XXXX____,
  __X__XX_,XXXXXXX_,________,
  _XX__XX_,X_____X_,________,
  XX___X__,______X_,________,
  _____X__,______X_,________,
  _____X__,______X_,________,
  _____X__,_______X,________,
  ________,_______X,________,
  ________,_______X,________,
  ________,_______X,________,
  ________,_______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ_HWXW24_949C[ 51] = { /* code 949C */
  _______X,________,________,
  ______XX,X_______,________,
  ______XX,__XXXXXX,X_______,
  _____XXX,XXXXXXXX,X_______,
  _____XX_,XX_XXXX_,________,
  ____XX__,__XX____,________,
  ___XX_XX,__XX__XX,X_______,
  ___XXXXX,__XXXXXX,XXX_____,
  _XXXXXX_,__XX___X,XX______,
  XXX_XXXX,__X___XX,XX______,
  _____XXX,__X__XXX,X_______,
  __XXXXX_,__XXXX__,________,
  __XXXX__,__X_____,________,
  ____X__X,__XX____,__X_____,
  ____XXXX,__XXXXXX,XXXX____,
  ____XXX_,__XXXXXX,XXXX____,
  _____X__,__X_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ_HWXW24_9650[ 51] = { /* code 9650 */
  ________,_XXXXX__,________,
  __XXX___,XXXXXX__,________,
  XX_XX___,XX__X___,________,
  X__X____,X___X___,________,
  X__X____,XXX_X___,________,
  X__X____,XXXX____,________,
  X__X____,X__X____,________,
  XXXX____,XXXX__X_,________,
  XXXX____,XX__XXXX,________,
  X__X___X,XX_XXX__,________,
  X______X,XXXX____,________,
  X______X,__XXX___,________,
  X_____X_,____XXX_,________,
  X_____X_,______XX,X_______,
  X_____X_,_XX___XX,XXX_____,
  X_____XX,XX_____X,XXXX____,
  ______XX,________,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontHZ_HWXW24_CharInfo[12] = {
   {  21,  17,   2,   2,  24, acGUI_FontHZ_HWXW24_516C } /* code 516C */
  ,{  15,  17,   4,   3,  24, acGUI_FontHZ_HWXW24_53F8 } /* code 53F8 */
  ,{  17,  20,   3,   1,  24, acGUI_FontHZ_HWXW24_5733 } /* code 5733 */
  ,{  21,  18,   1,   3,  24, acGUI_FontHZ_HWXW24_597D } /* code 597D */
  ,{  19,  23,   3,   0,  24, acGUI_FontHZ_HWXW24_5E02 } /* code 5E02 */
  ,{  21,  18,   2,   3,  24, acGUI_FontHZ_HWXW24_6280 } /* code 6280 */
  ,{  18,  20,   2,   1,  24, acGUI_FontHZ_HWXW24_6709 } /* code 6709 */
  ,{  16,  16,   4,   3,  24, acGUI_FontHZ_HWXW24_6DA6 } /* code 6DA6 */
  ,{  21,  17,   3,   3,  24, acGUI_FontHZ_HWXW24_6DF1 } /* code 6DF1 */
  ,{  20,  22,   2,   0,  24, acGUI_FontHZ_HWXW24_79D1 } /* code 79D1 */
  ,{  20,  17,   2,   2,  24, acGUI_FontHZ_HWXW24_949C } /* code 949C */
  ,{  20,  17,   3,   3,  24, acGUI_FontHZ_HWXW24_9650 } /* code 9650 */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ_HWXW24_Prop12 = {
   0x9650 /* first character */
  ,0x9650 /* last character  */
  ,&GUI_FontHZ_HWXW24_CharInfo[ 11] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ_HWXW24_Prop11 = {
   0x949C /* first character */
  ,0x949C /* last character  */
  ,&GUI_FontHZ_HWXW24_CharInfo[ 10] /* address of first character */
  ,&GUI_FontHZ_HWXW24_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ_HWXW24_Prop10 = {
   0x79D1 /* first character */
  ,0x79D1 /* last character  */
  ,&GUI_FontHZ_HWXW24_CharInfo[  9] /* address of first character */
  ,&GUI_FontHZ_HWXW24_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ_HWXW24_Prop9 = {
   0x6DF1 /* first character */
  ,0x6DF1 /* last character  */
  ,&GUI_FontHZ_HWXW24_CharInfo[  8] /* address of first character */
  ,&GUI_FontHZ_HWXW24_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ_HWXW24_Prop8 = {
   0x6DA6 /* first character */
  ,0x6DA6 /* last character  */
  ,&GUI_FontHZ_HWXW24_CharInfo[  7] /* address of first character */
  ,&GUI_FontHZ_HWXW24_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ_HWXW24_Prop7 = {
   0x6709 /* first character */
  ,0x6709 /* last character  */
  ,&GUI_FontHZ_HWXW24_CharInfo[  6] /* address of first character */
  ,&GUI_FontHZ_HWXW24_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ_HWXW24_Prop6 = {
   0x6280 /* first character */
  ,0x6280 /* last character  */
  ,&GUI_FontHZ_HWXW24_CharInfo[  5] /* address of first character */
  ,&GUI_FontHZ_HWXW24_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ_HWXW24_Prop5 = {
   0x5E02 /* first character */
  ,0x5E02 /* last character  */
  ,&GUI_FontHZ_HWXW24_CharInfo[  4] /* address of first character */
  ,&GUI_FontHZ_HWXW24_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ_HWXW24_Prop4 = {
   0x597D /* first character */
  ,0x597D /* last character  */
  ,&GUI_FontHZ_HWXW24_CharInfo[  3] /* address of first character */
  ,&GUI_FontHZ_HWXW24_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ_HWXW24_Prop3 = {
   0x5733 /* first character */
  ,0x5733 /* last character  */
  ,&GUI_FontHZ_HWXW24_CharInfo[  2] /* address of first character */
  ,&GUI_FontHZ_HWXW24_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ_HWXW24_Prop2 = {
   0x53F8 /* first character */
  ,0x53F8 /* last character  */
  ,&GUI_FontHZ_HWXW24_CharInfo[  1] /* address of first character */
  ,&GUI_FontHZ_HWXW24_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ_HWXW24_Prop1 = {
   0x516C /* first character */
  ,0x516C /* last character  */
  ,&GUI_FontHZ_HWXW24_CharInfo[  0] /* address of first character */
  ,&GUI_FontHZ_HWXW24_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontHZ_HWXW24 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontHZ_HWXW24_Prop1}
  ,18 /* Baseline */
  ,12 /* Height of lowercase characters */
  ,17 /* Height of capital characters */
};

